In [1]:
import pandas as pd

final_df = pd.read_csv(
    "../../datasets/SAM40/sam40_features.csv"
)

final_df.head()

,0,1,2,3,4,5,6,7,8,9,...,280,281,282,283,284,285,286,287,stress_score,stress_class
0,-0.074657,6.740791,45.438258,6.741204,-0.045287,6.253516,39.106461,6.253680,-0.029643,5.741403,...,8.389438,16.541257,9.383178,25.704150,17.331116,13.121828,23.224801,13.082408,3,Low
1,0.092489,7.091745,50.292846,7.092348,0.081880,6.224445,38.743720,6.224984,0.153716,6.056759,...,5.987932,17.758285,14.116481,15.682007,14.457869,9.014670,27.594673,19.482401,4,Medium
2,-0.037182,7.060756,49.854273,7.060854,-0.042347,6.323398,39.985367,6.323540,-0.071464,5.961646,...,6.703407,17.580674,12.483964,17.913242,14.299978,9.980425,28.898009,18.531803,6,Medium
3,0.060104,7.170137,51.410859,7.170388,0.212066,9.380086,87.986015,9.382483,0.145558,10.360620,...,15.366263,32.413479,26.908263,29.458650,27.280555,19.433629,47.427225,34.391778,7,High
4,0.031028,6.664629,44.417278,6.664701,0.047204,9.337539,87.189636,9.337658,0.104286,9.888134,...,16.107026,36.995017,28.410412,27.899519,24.152146,22.319953,45.406802,33.285317,6,Medium

In [2]:
print(final_df.shape)

print(final_df.columns[-5:])

(360, 290)
Index(['285', '286', '287', 'stress_score', 'stress_class'], dtype='str')

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X = final_df.drop(
    columns=["stress_score", "stress_class"]
)

y = final_df["stress_class"]

encoder = LabelEncoder()
y = encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train:", X_train.shape)
print("Test :", X_test.shape)

Train: (288, 288)
Test : (72, 288)

In [4]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

rf_preds = rf.predict(X_test)

In [5]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

rf_accuracy = accuracy_score(y_test, rf_preds)
rf_precision = precision_score(
    y_test,
    rf_preds,
    average="weighted"
)

rf_recall = recall_score(
    y_test,
    rf_preds,
    average="weighted"
)

rf_f1 = f1_score(
    y_test,
    rf_preds,
    average="weighted"
)

print("Accuracy :", rf_accuracy)
print("Precision:", rf_precision)
print("Recall   :", rf_recall)
print("F1 Score :", rf_f1)

print("\nClassification Report\n")
print(
    classification_report(
        y_test,
        rf_preds,
        target_names=encoder.classes_
    )
)

print("\nConfusion Matrix\n")
print(confusion_matrix(y_test, rf_preds))

Accuracy : 0.5277777777777778
Precision: 0.5266013071895425
Recall   : 0.5277777777777778
F1 Score : 0.5023671997356208

Classification Report

              precision    recall  f1-score   support

        High       0.60      0.21      0.32        14
         Low       0.41      0.35      0.38        20
      Medium       0.56      0.74      0.64        38

    accuracy                           0.53        72
   macro avg       0.52      0.43      0.44        72
weighted avg       0.53      0.53      0.50        72


Confusion Matrix

[[ 3  2  9]
 [ 0  7 13]
 [ 2  8 28]]

In [6]:
print("Train Accuracy:",
      rf.score(X_train, y_train))

print("Test Accuracy:",
      rf.score(X_test, y_test))

Train Accuracy: 1.0
Test Accuracy: 0.5277777777777778

In [7]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

svm = SVC(kernel="rbf")

svm.fit(X_train, y_train)

svm_preds = svm.predict(X_test)

print("Accuracy :", accuracy_score(y_test, svm_preds))
print("Precision:", precision_score(y_test, svm_preds, average="weighted"))
print("Recall   :", recall_score(y_test, svm_preds, average="weighted"))
print("F1 Score :", f1_score(y_test, svm_preds, average="weighted"))

Accuracy : 0.5416666666666666
Precision: 0.5602503912363067
Recall   : 0.5416666666666666
F1 Score : 0.39444687151109176

e:\Projects\EEG-Signals\venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
results = pd.DataFrame(columns=[
    "Model",
    "Accuracy",
    "Precision",
    "Recall",
    "F1"
])

In [10]:
from sklearn.neural_network import MLPClassifier

In [11]:
print(final_df["stress_score"].value_counts().sort_index())

stress_score
1     19
2     25
3     58
4     54
5     77
6     57
7     32
8     24
9     10
10     4
Name: count, dtype: int64

In [12]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

X = final_df.drop(columns=["stress_score", "stress_class"])
y = final_df["stress_score"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

preds = rf.predict(X_test)

print("MAE:", mean_absolute_error(y_test, preds))

MAE: 1.4079861111111112

In [13]:
import tensorflow as tf

print(tf.__version__)

2.21.0

In [14]:
print(final_df.shape)
print(final_df.columns[-5:])

(360, 290)
Index(['285', '286', '287', 'stress_score', 'stress_class'], dtype='str')

In [15]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

X = final_df.drop(
    columns=["stress_score", "stress_class"]
)

y = final_df["stress_class"]

encoder = LabelEncoder()
y = encoder.fit_transform(y)

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(288, 288)
(72, 288)

In [16]:
X_train_cnn = X_train.reshape(
    X_train.shape[0],
    X_train.shape[1],
    1
)

X_test_cnn = X_test.reshape(
    X_test.shape[0],
    X_test.shape[1],
    1
)

print(X_train_cnn.shape)
print(X_test_cnn.shape)

(288, 288, 1)
(72, 288, 1)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Flatten, Dense, Dropout

cnn = Sequential([
    Conv1D(
        filters=32,
        kernel_size=3,
        activation="relu",
        input_shape=(288, 1)
    ),

    MaxPooling1D(pool_size=2),

    Conv1D(
        filters=64,
        kernel_size=3,
        activation="relu"
    ),

    MaxPooling1D(pool_size=2),

    Flatten(),

    Dense(64, activation="relu"),

    Dropout(0.3),

    Dense(3, activation="softmax")
])

cnn.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

cnn.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

e:\Projects\EEG-Signals\venv\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 286, 32)        │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 143, 32)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 141, 64)        │         6,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 70, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 4480)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │       286,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 293,315 (1.12 MB)

 Trainable params: 293,315 (1.12 MB)

 Non-trainable params: 0 (0.00 B)

In [18]:
history = cnn.fit(
    X_train_cnn,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 3s 103ms/step - accuracy: 0.4609 - loss: 1.0810 - val_accuracy: 0.4310 - val_loss: 1.0817
Epoch 2/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5435 - loss: 0.9959 - val_accuracy: 0.4310 - val_loss: 1.0824
Epoch 3/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5435 - loss: 0.9582 - val_accuracy: 0.4310 - val_loss: 1.0544
Epoch 4/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5609 - loss: 0.9412 - val_accuracy: 0.4310 - val_loss: 1.0255
Epoch 5/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5478 - loss: 0.9036 - val_accuracy: 0.4310 - val_loss: 1.0279
Epoch 6/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5652 - loss: 0.8882 - val_accuracy: 0.4655 - val_loss: 0.9848
Epoch 7/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5957 - loss: 0.8398 - val_accuracy: 0.4310 - val_loss: 1.0759
Epoch 8/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6435 - loss: 0.8030 - val_accuracy: 0.4828 - val_loss: 1.0126
Epoch 9/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6478 - loss: 0.7743 - val_accuracy: 0.5517 - val_loss: 0.9676
Epoch 10/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6435 - loss: 0.7451 - val_accuracy: 0.5517 - val_loss: 0.9518
Epoch 11/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6870 - loss: 0.7531 - val_accuracy: 0.4483 - val_loss: 1.0715
Epoch 12/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6696 - loss: 0.7289 - val_accuracy: 0.5517 - val_loss: 0.9681
Epoch 13/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7435 - loss: 0.6986 - val_accuracy: 0.4310 - val_loss: 1.1267
Epoch 14/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7304 - loss: 0.6591 - val_accuracy: 0.5345 - val_loss: 0.9646
Epoch 15/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7391 - loss: 0.6077 - val_accuracy: 0.5000 - val_loss: 1.0457
Epoch 16/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7130 - loss: 0.5960 - val_accuracy: 0.5862 - val_loss: 0.9653
Epoch 17/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7870 - loss: 0.5481 - val_accuracy: 0.5345 - val_loss: 1.0416
Epoch 18/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7565 - loss: 0.5399 - val_accuracy: 0.5345 - val_loss: 0.9587
Epoch 19/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7870 - loss: 0.5766 - val_accuracy: 0.4828 - val_loss: 1.1241
Epoch 20/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7957 - loss: 0.5028 - val_accuracy: 0.5690 - val_loss: 1.0024

In [19]:
test_loss, test_acc = cnn.evaluate(
    X_test_cnn,
    y_test,
    verbose=0
)

print("Test Accuracy:", test_acc)

Test Accuracy: 0.5

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

lstm = Sequential([
    LSTM(
        64,
        input_shape=(288, 1)
    ),

    Dropout(0.3),

    Dense(32, activation="relu"),

    Dense(3, activation="softmax")
])

lstm.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

lstm.summary()

e:\Projects\EEG-Signals\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 64)             │        16,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,075 (74.51 KB)

 Trainable params: 19,075 (74.51 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
history = lstm.fit(
    X_train_cnn,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 122ms/step - accuracy: 0.3652 - loss: 1.0861 - val_accuracy: 0.5690 - val_loss: 1.0750
Epoch 2/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 131ms/step - accuracy: 0.4957 - loss: 1.0510 - val_accuracy: 0.5690 - val_loss: 1.0571
Epoch 3/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 90ms/step - accuracy: 0.5087 - loss: 1.0270 - val_accuracy: 0.4655 - val_loss: 1.0525
Epoch 4/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - accuracy: 0.5478 - loss: 1.0169 - val_accuracy: 0.4310 - val_loss: 1.0467
Epoch 5/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 92ms/step - accuracy: 0.5348 - loss: 1.0066 - val_accuracy: 0.4310 - val_loss: 1.0426
Epoch 6/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 122ms/step - accuracy: 0.5391 - loss: 0.9864 - val_accuracy: 0.4138 - val_loss: 1.0642
Epoch 7/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - accuracy: 0.5478 - loss: 0.9763 - val_accuracy: 0.4138 - val_loss: 1.0817
Epoch 8/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - accuracy: 0.5435 - loss: 0.9664 - val_accuracy: 0.4138 - val_loss: 1.0910
Epoch 9/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - accuracy: 0.5391 - loss: 0.9787 - val_accuracy: 0.4138 - val_loss: 1.0639
Epoch 10/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 75ms/step - accuracy: 0.5391 - loss: 0.9662 - val_accuracy: 0.4138 - val_loss: 1.0555
Epoch 11/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - accuracy: 0.5435 - loss: 0.9631 - val_accuracy: 0.4138 - val_loss: 1.0772
Epoch 12/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - accuracy: 0.5522 - loss: 0.9604 - val_accuracy: 0.4310 - val_loss: 1.0659
Epoch 13/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - accuracy: 0.5435 - loss: 0.9540 - val_accuracy: 0.4310 - val_loss: 1.0491
Epoch 14/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - accuracy: 0.5435 - loss: 0.9632 - val_accuracy: 0.4310 - val_loss: 1.0522
Epoch 15/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 75ms/step - accuracy: 0.5391 - loss: 0.9626 - val_accuracy: 0.4483 - val_loss: 1.0689
Epoch 16/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - accuracy: 0.5522 - loss: 0.9482 - val_accuracy: 0.3966 - val_loss: 1.1006
Epoch 17/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 76ms/step - accuracy: 0.5391 - loss: 0.9427 - val_accuracy: 0.3966 - val_loss: 1.0526
Epoch 18/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 76ms/step - accuracy: 0.5304 - loss: 0.9446 - val_accuracy: 0.4138 - val_loss: 1.0497
Epoch 19/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - accuracy: 0.5696 - loss: 0.9353 - val_accuracy: 0.4310 - val_loss: 1.0325
Epoch 20/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - accuracy: 0.5609 - loss: 0.9221 - val_accuracy: 0.4310 - val_loss: 1.0010

In [22]:
test_loss, test_acc = lstm.evaluate(
    X_test_cnn,
    y_test,
    verbose=0
)

print("LSTM Accuracy:", test_acc)

LSTM Accuracy: 0.5833333134651184

In [24]:
results = pd.DataFrame({
    "Model": [
        "Random Forest",
        "SVM",
        "1D CNN",
        "LSTM"
    ],
    "Accuracy": [
        0.5278,
        0.5417,
        0.5000,
        0.5833
    ],
    "Precision": [
        0.5266,
        0.5603,
        None,
        None
    ],
    "Recall": [
        0.5278,
        0.5417,
        None,
        None
    ],
    "F1": [
        0.5024,
        0.3944,
        None,
        None
    ]
})

results

           Model  Accuracy  Precision  Recall      F1
0  Random Forest    0.5278     0.5266  0.5278  0.5024
1            SVM    0.5417     0.5603  0.5417  0.3944
2         1D CNN    0.5000        NaN     NaN     NaN
3           LSTM    0.5833        NaN     NaN     NaN